FROM node:12.13.1-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.17.9-alpine AS app
WORKDIR /app
COPY --from=builder /app/build /usr/share/nginx/html
